spring:
  r2dbc:
    username: toptweets
    password: pgpassword
    url: r2dbc:postgresql://localhost:5432/toptweets
    pool.initial-size: 10
    pool.max-size: 50
    pool.max-idle-time: 30m
    pool.validation-query: SELECT 1
  flyway:
    enabled: true
    url: jdbc:postgresql://localhost:5432/toptweets
    user: ${spring.r2dbc.username}
    password: ${spring.r2dbc.password}
    baseline-on-migrate: true
    locations: classpath:db/migration

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-jecc6018.us.auth0.com/

auth0:
  audience: http://sma-control/api



#
#  security:
#    oauth2:
#      client:
#        registration:
#          auth0:
#            client-id: dFpvB2TZww9kAk9OGWRXryqkNPHX6OAK
#            client-secret: RXHcVZ1awkjv_nrwTdgrpQUBA1d4GR4OJqIf-5SC893M7k3LDKD1weh4ENfEnYzU
#            scope:
#              - openid
#              - profile
#              - email
#        provider:
#          auth0:
#            # trailing slash is important!
#            issuer-uri: https://YOUR_DOMAIN/
#auth0.audience=
#auth0.domain=
#spring.security.oauth2.resourceserver.jwt.issuer-uri=https://${auth0.domain}/