/**
  SMA schema
 */
create schema sma;

create table sma.user
(
    id           integer GENERATED BY DEFAULT AS IDENTITY not null primary key,
    auth_id      text                                     not null unique,
    enabled      boolean                                  not null default true,
    created_date timestamp                                not null default current_timestamp
);

create table sma.account
(
    id                    interval GENERATED BY DEFAULT AS IDENTITY not null primary key,
    user_id               integer                                   not null,
    external_account_id   text                                      not null,
    external_account_type text                                      not null,
    created_date          timestamp                                 not null default current_timestamp,
    enabled               boolean                                   not null default true,
    foreign key (user_id) references sma.user (id)
);

/**
  Twitter schema
 */
create schema twitter;

create table twitter.content_options
(
    account_id              integer  not null,
    show_possibly_sensitive boolean  not null default false,
    show_with_media_only    boolean  not null default false,
    show_replies            boolean  not null default true,
    show_retweets           boolean  not null default true,
    last_number_of_days     smallint not null default 7
);
create table twitter.language
(
    language   text    not null,
    account_id integer not null,
    foreign key (account_id) references sma.account (id)
);
create table twitter.author
(
    tw_user_id text    not null,
    account_id integer not null,
    foreign key (account_id) references sma.account (id)
);
create table twitter.user_mention
(
    tw_user_id text    not null,
    account_id integer not null,
    foreign key (account_id) references sma.account (id)
);

create table twitter.hashtag
(
    tag        text    not null,
    account_id integer not null,
    foreign key (account_id) references sma.account (id)
);
create table twitter.place
(
    place      text    not null,
    account_id integer not null,
    foreign key (account_id) references sma.account (id)
);
create table twitter.filtered_search_rule
(
    rule_id    text    not null,
    rule_query text    not null,
    rule_tag   text    not null,
    account_id integer not null,
    foreign key (account_id) references sma.account (id)
);